### ISSUE TITLE
How to export labels?

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#1]
Hi!
Thank you for this great software!

I have a question about how to export labels?

**Comment by mingrui** [comment]
figured it out

when creating a new database, the software will automatically prompt you to save the current one in use.

**Comment by maubreville** [comment]
Actually, this is a misunderstanding I'm afraid. The software will open the default DB (Slides.sqlite in the user's home directory). 

But I should make this more clear. Perhaps even a dedicated option to export the current DB would be good.

**Comment by maubreville** [comment]
It is indeed kept in the file system all the time (it's an sqlite database, after all). All changes are stored directly to the DB file.

I changed the label in the menu in the current CVS version, hope this makes the DB interaction a little bit clearer. When time permits I want to enable the possibility to store the DB to a new copy.
