### ISSUE TITLE
minor usability enhancement: dragging lags when dragging across patches

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#10]
This is related to: https://github.com/maubreville/SlideRunner/issues/2

It's a minor problem, hoping for an enhancement if you have the time for it.
It's now much faster when dragging, but one problem I encountered is when dragging across patches.

Within a patch, the dragging is smooth, but pass a certain line across another patch, it lags a little bit (I assume its loading the very high resolution patch). Maybe change it to load a low resolution zoom level first to avoid the jarring jumping effect.
Here is a video to better explain:  https://drive.google.com/open?id=1yFCt99kQ-8GWVZ1vvA7AXRdgtjkS03m0

**Comment by mingrui** [comment]
I just tried the update and think it's much improved. Most of the time I'm using the highest zoom level and dragging around is much better than before. Thanks for the update!

**Comment by maubreville** [comment]
I feel that this issue might not really be solved, but I do not see an easy and architecturally simple way to do it. If you feel that this is important for you, feel free to reopen the issue.
