### ISSUE TITLE
Clarification needed: When adding second label, spot label circle disappears

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#11]
Using the spot tool, when adding a second label, the circle disappears.

(The spot circle not generating directly under the mouse is an issue related to my i3 window manager, it does not happen on regular ubuntu, please ignore)

Here is the bug in action: https://drive.google.com/file/d/15vQ4n6LfcNj04k7sH47N6-qFUC-uksmT/view?usp=sharing

Looking at the database, its a successful write: https://drive.google.com/open?id=1PUURbeD8SbDkzpnBhGDjjiY1DVx5fV9B

**Comment by mingrui** [comment]
Actually, I think this is not a bug...

The circle disappears because if you add a different second label, the there is a difference of opinion between two experts, so the labels cancel each other out.

In the database, the Annotations.agreedClass will be 0

Could we get a clarification if this is the case? Thank you!

**Comment by maubreville** [comment]
Thanks for this nicely made report. The "agreed class" is always 0 if both annotators disagree. I think that it's however weird, that the unknown labels are turned on by default.

**Comment by maubreville** [comment]
Do you think it's fixed for you, if unknown class annotations are enabled by default?

**Comment by mingrui** [comment]
Just tried the update, I think 1. it's much more clear now; 2. The black circle gives me a chance to re-evaluate differences in opinion at a later time.

I think unknown label enabled by default works for me.

Thanks for the update!
