### ISSUE TITLE
Bug: Polygon right click, can't finish annotation

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#13]
This is a minor bug.

Using the polygon tool, at the end of my annotation, if I double left click, I can finish my annotation successfully.

But if I right click, the annotation does not finish.

But in action from two testers: 
https://drive.google.com/open?id=1MOGNLfxnI-xveBQHh9RJDi-0crtwCpVI
https://drive.google.com/open?id=1IVcImFgAUxheTR9tTAXlSUmklXktgrnl <<< sound on this one, caution

**Comment by maubreville** [comment]
Interesting that I've never stumbled across this....
