### ISSUE TITLE
Started a helper / plugin project

### ISSUE THREAD

**Issue by mingrui** [maubreville/SlideRunner#15]
Started working on a helper / plugin to this project.
This simple tool will cut ROI patches based on your annotations, then you can feed the patches to your deep learning network.

https://github.com/mingrui/SlideRunner-ROI-Patch-Maker

**Comment by maubreville** [comment]
Very cool! I will link it in the Readme.md!

**Comment by maubreville** [comment]
It's references in README - so I fix this issue.
