### ISSUE TITLE
Download for MacOS is not a zipfile

### ISSUE THREAD

**Issue by DanRuderman** [maubreville/SlideRunner#25]
Just downloaded the MacOS release zip file. Zip didn't recognize its contents, which are:

`version https://git-lfs.github.com/spec/v1
oid sha256:b16d5c0613a2e4b8ba1393045b09530cbb0c99632125721b8e8deba7a0348609
size 281423076`

Creating from scratch by downloading the repository and running `python setup.py install` gives a similar result.

Thank you.

**Comment by maubreville** [comment]
Dear Dan,

I am sorry to hear. Last time I checked it was working. 

A friend also got an error related to a non decimal version of some of the required packages. I am currently on vacation with only my iPhone with me. I tried to resolve the issue in 6aa3546. Could you try to clone again / pull and see if it works?

Best
Marv

**Comment by DanRuderman** [comment]
Thanks, Marv. I downloaded anew and ran `python setup.py install`. In the resulting dist/ directory I see:

>-rw-r--r--@ 1 ruderman  staff    86M Sep  8 22:18 SlideRunner.exe
>-rw-r--r--@ 1 ruderman  staff   134B Sep  8 22:18 SlideRunner.app.zip
>-rw-r--r--    1 ruderman  staff   426K Sep  9 06:48 SlideRunner-1.26.0-py3.6.egg

So it only updated the egg file ("Sep 9"). I successfully ran `easy_install` on the egg file, but I'm not clear on how to execute SlideRunner now that it's installed. Understand you're on vacation, so no need to respond right away. Many thanks.

**Comment by maubreville** [comment]
Dear Dan,

after a 'python setup.py develop' you should have the script sliderunner in your path. If not, you can try to run main.py within the SlideRunner folder.

I'll be back from vacation in a week and will or an updated version of the Mac app bundle on the site then.

Best regards
Marc

**Comment by DanRuderman** [comment]
Thank you!

**Comment by maubreville** [comment]
Dear Dan,

I tried to compile the current version with pyinstaller for Mac OS now for some hours, yet without success. Do you think it's possible to give it another shot with the source code? I'm back from holiday now and should things not work out, we could also try to have a skype call and fix it together.

Best regards,

Marc

**Comment by DanRuderman** [comment]
Thanks, Marc. I was able to get it to run using 'python setup.py develop' and then running the script sliderunner.

**Comment by maubreville** [comment]
That's great. I hope it is useful for your purpose.

**Comment by maubreville** [comment]
The latest version is uploaded and should be fine.
