### ISSUE TITLE
Arbitrary offset in annotation

### ISSUE THREAD

**Issue by maubreville** [maubreville/SlideRunner#4]
Sometimes the annotations appear with a perceivable offset. Needs to be investigated why this happens.

**Comment by mingrui** [comment]
I have experienced the same problem with Spot annotation tool

**Comment by maubreville** [comment]
Strangely enough, it seems to be fixed when resizing the application.

**Comment by maubreville** [comment]
Should be fixed with latest check-in.

**Comment by mingrui** [comment]
Can confirm it's fixed for me, thx!
